// <auto-generated />
namespace DM.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PatientMedicalInfo_Entity_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatientMedicalInfo_Entity_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202309011808374_PatientMedicalInfo_Entity_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
